#!/usr/bin/env python3
"""Project-native validation gate for CoreReplica.

Validates deterministic plugin/governance invariants already encoded in project
authorities, self-tests representative known-bad mutants, then runs the Python
regression suite.
"""

import csv
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS = [
    "corereplica-orchestration",
    "corereplica-reference",
    "corereplica-product",
    "corereplica-design",
    "corereplica-build",
    "corereplica-verify",
    "corereplica-market",
    "corereplica-release",
]
REQUIRED_DOCS = [
    "docs/USER_VISION.md",
    "docs/DECISION_COMPENDIUM.md",
    "docs/SYSTEM_MAP.yaml",
    "docs/CAPABILITY_GRAPH.yaml",
    "docs/SYSTEM_INTEGRATION.yaml",
    "docs/ARCHITECTURE_GUARDRAILS.yaml",
    "docs/PRODUCT_REALIZATION.yaml",
    "docs/PROJECT_PLAN.yaml",
    "docs/ACCEPTANCE.yaml",
    "docs/PROJECT_INDEX.yaml",
    "docs/CONTEXT_HANDOFF.md",
    "SOURCE_PROVENANCE.md",
    "LICENSE",
    "LICENSE-UPSTREAM",
    "THIRD_PARTY_NOTICES.md",
]
FORBIDDEN_STATUS_FIELDS = {"clone", "done", "verified", "implementation_status"}
FORBIDDEN_PACKAGE_PARTS = {"__pycache__", ".pytest_cache", ".mypy_cache", "node_modules", ".venv", "venv"}
FORBIDDEN_PACKAGE_SUFFIXES = {".pyc", ".pyo"}


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return fh.read()


def error(errors, message):
    errors.append(message)


def check_requirement_fields(fields):
    bad = sorted(FORBIDDEN_STATUS_FIELDS.intersection(f.lower() for f in fields))
    return [] if not bad else ["Product requirements contain forbidden state fields: %s" % ", ".join(bad)]


def check_verifier_text(text):
    low = text.lower()
    errors = []
    if "read-only" not in low:
        errors.append("Verifier lost read-only contract")
    if "do **not** fix source implementation" not in low:
        errors.append("Verifier no longer explicitly forbids self-fixing")
    if "## step 5: fix loop" in low or "fix loop" in low:
        errors.append("Verifier contains a fix loop")
    if "route the finding" not in low:
        errors.append("Verifier no longer routes findings to implementation owner")
    return errors


def check_release_text(text):
    low = text.lower()
    errors = []
    for phrase in ("reversible preparation", "exact gated transition", "explicit current approval"):
        if phrase not in low:
            errors.append("Release gate missing phrase: %s" % phrase)
    return errors


def check_orchestration_text(text):
    errors = []
    if "REFERENCE TRUTH != PRODUCT TRUTH != IMPLEMENTATION STATE != VERIFICATION TRUTH != RELEASE APPROVAL" not in text:
        errors.append("Orchestration lost truth-layer separation")
    if "Do not preload all siblings" not in text:
        errors.append("Orchestration lost JIT/progressive disclosure rule")
    if "recon -> architect -> design -> build -> backend -> test -> diff" in text.lower():
        errors.append("Mandatory upstream pipeline reintroduced")
    return errors



def check_package_hygiene(paths):
    errors = []
    for rel in paths:
        parts = set(rel.replace("\\", "/").split("/"))
        if parts.intersection(FORBIDDEN_PACKAGE_PARTS):
            errors.append("Generated/dependency directory must not ship: %s" % rel)
        if any(rel.endswith(suffix) for suffix in FORBIDDEN_PACKAGE_SUFFIXES):
            errors.append("Generated bytecode must not ship: %s" % rel)
    return errors


def repository_paths():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        for filename in filenames:
            out.append(os.path.relpath(os.path.join(dirpath, filename), ROOT))
    return out

def structural_checks():
    errors = []
    errors.extend(check_package_hygiene(repository_paths()))
    for rel in REQUIRED_DOCS:
        if not os.path.isfile(os.path.join(ROOT, rel)):
            error(errors, "Missing required authority/support file: %s" % rel)

    try:
        manifest = json.loads(read("plugin.json"))
    except Exception as exc:
        return ["plugin.json unreadable: %s" % exc]
    if manifest.get("name") != "corereplica":
        error(errors, "plugin name must be corereplica")
    if not re.match(r"^\d+\.\d+\.\d+$", str(manifest.get("version", ""))):
        error(errors, "plugin version must be strict semver")
    interface = manifest.get("extensions", {}).get("com.openai", {}).get("interface", {})
    short = interface.get("shortDescription", "")
    if not short or len(short) > 30:
        error(errors, "shortDescription must be 1..30 characters")

    skills_root = os.path.join(ROOT, "skills")
    found = sorted(
        d for d in os.listdir(skills_root)
        if os.path.isfile(os.path.join(skills_root, d, "SKILL.md"))
    )
    if found != sorted(SKILLS):
        error(errors, "skill set mismatch: %r" % found)

    for name in SKILLS:
        rel = "skills/%s/SKILL.md" % name
        text = read(rel)
        m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        if not m:
            error(errors, "%s has invalid frontmatter" % rel)
            continue
        fm = m.group(1)
        if "name: %s" % name not in fm:
            error(errors, "%s frontmatter name mismatch" % rel)
        if "description:" not in fm:
            error(errors, "%s missing description" % rel)

    for rel in (
        "skills/corereplica-reference/assets/feature-observations.csv",
        "skills/corereplica-product/assets/requirements.csv",
    ):
        with open(os.path.join(ROOT, rel), newline="", encoding="utf-8") as fh:
            fields = next(csv.reader(fh))
        if rel.endswith("requirements.csv"):
            errors.extend(check_requirement_fields(fields))
        else:
            bad = sorted({"priority"}.union(FORBIDDEN_STATUS_FIELDS).intersection(f.lower() for f in fields))
            if bad:
                error(errors, "Reference observations contain target/state fields: %s" % ", ".join(bad))

    errors.extend(check_orchestration_text(read("skills/corereplica-orchestration/SKILL.md")))
    errors.extend(check_verifier_text(read("skills/corereplica-verify/SKILL.md")))
    errors.extend(check_release_text(read("skills/corereplica-release/SKILL.md")))

    prov = read("SOURCE_PROVENANCE.md")
    if "77c9436fb3d18c3d58169efb8caf4fe906b0dc51" not in prov:
        error(errors, "upstream commit provenance missing")
    return errors


def self_test_mutants():
    failures = []
    if not check_requirement_fields(["id", "requirement", "priority", "clone"]):
        failures.append("requirements mutant with builder status was not rejected")

    verify = read("skills/corereplica-verify/SKILL.md") + "\n## Step 5: fix loop\nFix it yourself.\n"
    if not any("fix loop" in e.lower() for e in check_verifier_text(verify)):
        failures.append("verifier self-fix mutant was not rejected")

    release = read("skills/corereplica-release/SKILL.md").replace("explicit current approval", "approval")
    if not check_release_text(release):
        failures.append("release approval-boundary mutant was not rejected")

    orch = read("skills/corereplica-orchestration/SKILL.md").replace(
        "REFERENCE TRUTH != PRODUCT TRUTH != IMPLEMENTATION STATE != VERIFICATION TRUTH != RELEASE APPROVAL",
        "REFERENCE AND PRODUCT TRUTH ARE THE SAME",
    )
    if not check_orchestration_text(orch):
        failures.append("truth-layer collapse mutant was not rejected")

    if not check_package_hygiene(["skills/x/__pycache__/a.pyc"]):
        failures.append("package-hygiene mutant with generated bytecode was not rejected")
    return failures


def run_tests():
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    return subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"],
        cwd=ROOT,
        text=True,
        env=env,
    ).returncode


def main():
    errors = structural_checks()
    mutants = self_test_mutants()
    if errors:
        print("CoreReplica structural gate: FAIL")
        for e in errors:
            print("- %s" % e)
        return 1
    if mutants:
        print("CoreReplica validator self-test: FAIL")
        for e in mutants:
            print("- %s" % e)
        return 1
    print("CoreReplica structural gate: PASS")
    print("CoreReplica validator self-test: PASS")
    code = run_tests()
    if code:
        print("CoreReplica regression gate: FAIL")
        return code
    print("CoreReplica regression gate: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
